### ISSUE TITLE
Add ranking of published solutions

### ISSUE THREAD

**Issue by avegner** [exercism/website-copy#1238]
Hi there!

It would be nice to see how one's solution performs in comparison to others for a given task.
I mean ranking by time, memory and allocs. 
Can you (maintainers) add that to the website?

**Comment by kotp** [comment]
@avegner did you close this because you would not want to see such a thing?  Or did you change your mind about how this might fit?  Or perhaps this is more interesting on a specific track?  What are your thoughts?  (I can also imagine that you felt like this issue was never read, since there seems to be no remarks on it.  Sorry for that, if that is the case, I am pretty sure it has been at least read).

**Comment by avegner** [comment]
I still want to have and use such feature. Since there was no reaction to this issue I've created a new issue here: https://github.com/exercism/exercism/issues/5043
Moreover custom exercism-bench tool for Go track has been made:
https://github.com/avegner/exercism-bench

**Comment by kotp** [comment]
Thanks for providing the cross references.
