### ISSUE TITLE
Exception handling in High Scores exercise

### ISSUE THREAD

**Issue by kwikiel** [exercism/website-copy#1465]
[https://github.com/exercism/website-copy/blob/master/tracks/python/exercises/high-scores/mentoring.md](https://github.com/exercism/website-copy/blob/master/tracks/python/exercises/high-scores/mentoring.md)

It looks like an very good place to introduce meaningful and useful exception handling: if an empty list of scores is provided then max(scores) may return 0 instead of an IndexError.

**Comment by corneliusroemer** [comment]
What's your issue about? Do you ask for a mentor note to be added/changed? Or the exercise changed?

**Comment by kwikiel** [comment]
For the empty test case with the high scores some implementations may fail - so I was wondered if it's a good place to tell people about try except syntax.

**Comment by corneliusroemer** [comment]
I think that such things are not being changed right now for version 2. Version 3 is under active development and is concerned much more with didactics.

**Comment by angelikatyborska** [comment]
@kwikiel Each exercise has an Exercism-wide definition in a [problem-specifications repository](https://github.com/exercism/problem-specifications/). This particular exercise is meant to be very easy and the suggested test cases do not include any kind of error handling. See:
https://github.com/exercism/problem-specifications/blob/daf620d47ed905409564dec5fa9610664e294bde/exercises/high-scores/canonical-data.json#L4-L6

I think this is why there is no error handling in the Python implementation of this exercise. I'm guessing, because I personally have no connections to the Python track.

If you are certain adding error handling is a good idea for the Python track, I would recommend opening an issue in the [exercism/python repository](https://github.com/exercism/python/) instead, where you have a higher chance of getting the attention of Python maintainers.

I'm going to close this issue for now.
