### ISSUE TITLE
Where are the tutorials? 

### ISSUE THREAD

**Issue by Makebuildmodify** [exercism/website-copy#1616]
Is exercism for code testing and mentoring only or are there tutorials for each language? I can't find any tutorials.

**Comment by rahulkeerthi** [comment]
Hi @Makebuildmodify - Exercism doesn't include tutorials but maintainers of each track link to resources where you can learn more, either in the track introductions or where applicable, in exercise descriptions. Hope that clarifies!

**Comment by corneliusroemer** [comment]
It's called exercism for a reason - the website provides exercism and code review of solutions, not tutorials.

**Comment by angelikatyborska** [comment]
In Exercism v3, there will be learning exercises that teach specific concepts from a specific programming language, a bit like a tutorial.

At the beginning, they won't be available in all languages because not all languages have active maintainers that are writing those learning exercises. Exercism v3 is currently in beta and is scheduled to be released to production in 1-2 months.

I think that answers the question and the issue can be closed.
