### ISSUE TITLE
Broken link to JuliaPro

### ISSUE THREAD

**Issue by SJaffa** [exercism/website-copy#1968]
On the [Julia Installation](https://exercism.io/tracks/julia/installation) page the link to JuliaPro is broken. It should be https://juliacomputing.com/products/juliapro/

**Comment by angelikatyborska** [comment]
Hi! Thank you for reporting this problem. The contents of the Julia installations instructions belong to the `exercism/julia` repository. To be exact, they're in this file: https://github.com/exercism/julia/blob/main/docs/INSTALLATION.md

It looks like a month ago this file was updated and the broken link to JuliaPro was removed (see commit https://github.com/exercism/julia/commit/4d02d938c6d5fa9dd2bcef18ff12868a7aff2cee). However, because of  the work happening for Exercism v3, the current Exercism website is no longer synchronizing with the track repositories (since end of January 2021). That means that this broken link will unfortunately have to stay there until Exercism v3 is released.
