### ISSUE TITLE
Java & Kotlin : update installation commands for MacOs ( brew install ) 

### ISSUE THREAD

**Issue by Reunina** [exercism/website-copy#2009]
In the Kotlin installation documentation : [https://exercism.io/tracks/kotlin/installation](https://exercism.io/tracks/kotlin/installation)

the brew command is outdated : 

`brew cask install homebrew/cask-versions/java11`

should be 
`brew install --cask homebrew/cask-versions/java11`

[see this discussion]( https://github.com/Homebrew/discussions/discussions/902)

**Comment by angelikatyborska** [comment]
@Reunina would like to open a pull request with that change? This file needs an update: https://github.com/exercism/kotlin/blob/main/docs/INSTALLATION.md

For Java, the instructions were already updated (see; https://github.com/exercism/java/blob/main/docs/INSTALLATION.md) but due to work on Exercism v3 the content doesn't synchronize with exercism.io at the moment.

**Comment by Reunina** [comment]
yes :) 

I am on it as we speak ^^

**Comment by Reunina** [comment]
sorry it takes me longer than expected ( had to go to work ^^) 

here the PR : https://github.com/exercism/kotlin/pull/484

**Comment by angelikatyborska** [comment]
Closed in https://github.com/exercism/kotlin/pull/484
