### ISSUE TITLE
El_negro_willi #1:

### ISSUE THREAD

**Issue by WilsonbermudezMartinez** [exercism/website-copy#2341]
El_negro_willi #1: pregunta: porque los mensajes enviados desde github aparecen en la lista de correo electrónico (TODOS) no aparecen en el listado del correo electrónico (PRINCIPAL)??????? Es un poco lento el cursor en mi dispositivo móvil honor 6, andoid y este dispositivo es compatible con ejercicios = " exercism "???? +584260480129, aries21wil@gmail.com, Wilson bermudez Martinez

**Comment by angelikatyborska** [comment]
Hi! I think you created this GitHub Issue by accident. I am not really sure what you're asking because I don't speak Spanish, but it doesn't sound like it's related to this repository, but instead to managing your Github notifications and your email inbox. Maybe ask a friend for a help?

i think you also accidentally posted your phone number and email address in public. You might want to delete that.
